import { useState } from 'react';
import { X, Briefcase, MapPin, Building2, Wand2, FileText, SendHorizontal } from 'lucide-react';
import { JobFitScore } from '../../types/job';
import { api } from '../../lib/axios';
import { usePermissions } from '../../hooks/usePermissions';
import { FitScoreBadge } from './FitScoreBadge';

export function JobDetail({ jobScore, onClose }: { jobScore: JobFitScore, onClose: () => void }) {
  const { job, fit_score, fit_reasons } = jobScore;
  const { canViewFitReasons, canAutoApply } = usePermissions();

  const [tailoring, setTailoring] = useState(false);
  const [applying, setApplying] = useState(false);
  const [successMsg, setSuccessMsg] = useState<string | null>(null);

  const handleTailor = async () => {
    if (!canViewFitReasons) return;
    setTailoring(true);
    try {
      await api.post(`/api/agents/resume-tailor`, { job_id: job.job_id });
      setSuccessMsg('Resume tailored successfully! Check your dashboard.');
      setTimeout(() => setSuccessMsg(null), 3000);
    } catch (err) {
      console.error(err);
    } finally {
      setTailoring(false);
    }
  };

  const handleApply = async () => {
    if (!canAutoApply) {
      // Just mock manual application tracking for free users
      setSuccessMsg('Application logged manually.');
      setTimeout(() => setSuccessMsg(null), 3000);
      return;
    }

    setApplying(true);
    try {
      await api.post(`/api/agents/auto-apply`, { job_id: job.job_id });
      setSuccessMsg('Auto-apply initiated! You will see it in the Applications tab shortly.');
      setTimeout(() => setSuccessMsg(null), 3000);
    } catch (err) {
      console.error(err);
    } finally {
      setApplying(false);
    }
  };

  return (
    <div className="fixed inset-0 z-40 bg-slate-900/50 backdrop-blur-sm flex items-end sm:items-center justify-center sm:p-4">
      <div className="bg-white w-full sm:max-w-2xl h-[90vh] sm:h-[80vh] sm:rounded-2xl shadow-xl flex flex-col relative animate-in fade-in zoom-in-95 duration-200">

        {/* Header */}
        <div className="flex items-center justify-between p-6 pl-8 border-b border-slate-100">
          <div>
            <h2 className="text-2xl font-bold text-slate-900 pr-8">{job.title}</h2>
            <div className="flex items-center text-slate-500 mt-1">
              <Building2 className="w-4 h-4 mr-1.5" />
              <span className="font-medium mr-4">{job.company}</span>
              <FitScoreBadge score={fit_score} />
            </div>
          </div>
          <button
            onClick={onClose}
            className="absolute top-6 right-6 p-2 rounded-full hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8">
          {successMsg && (
            <div className="mb-6 p-4 bg-green-50 border border-green-200 text-green-700 rounded-xl flex items-center">
              <span className="font-medium">{successMsg}</span>
            </div>
          )}

          <div className="flex flex-wrap gap-4 mb-8">
            <div className="flex items-center text-slate-700 bg-slate-50 px-3 py-1.5 rounded-lg border border-slate-200">
              <MapPin className="w-4 h-4 mr-2 text-slate-400" />
              {job.location} {job.is_remote && <span className="text-slate-400 ml-1">(Remote)</span>}
            </div>
            <div className="flex items-center text-slate-700 bg-slate-50 px-3 py-1.5 rounded-lg border border-slate-200">
              <Briefcase className="w-4 h-4 mr-2 text-slate-400" />
              {job.role_family}
            </div>
          </div>

          <div className="mb-8">
            <h3 className="text-lg font-bold text-slate-900 mb-3 border-b-2 border-primary/20 inline-block pb-1">AI Match Analysis</h3>
            <div className={`p-5 rounded-xl border border-slate-200 bg-slate-50/50 ${!canViewFitReasons ? 'blur-sm pointer-events-none select-none relative h-24 overflow-hidden' : ''}`}>
              <p className="text-slate-700 text-sm leading-relaxed whitespace-pre-wrap">
                {fit_reasons || 'Detailed fit reasoning is generated by our AI based on your skills, experience, and employer requirements.'}
              </p>
            </div>
            {!canViewFitReasons && (
              <p className="text-sm text-slate-500 italic mt-3 text-center">Unlock Talvix Pro to view detailed AI suitability analysis.</p>
            )}
          </div>

          <div>
            <h3 className="text-lg font-bold text-slate-900 mb-3 border-b-2 border-primary/20 inline-block pb-1">Job Details</h3>
            <div className="prose prose-sm max-w-none text-slate-600">
              <p>Description tracking placeholder. Full JD is accessible via API / DB join if needed.</p>
            </div>
          </div>
        </div>

        {/* Action Footer */}
        <div className="p-6 border-t border-slate-100 bg-slate-50 sm:rounded-b-2xl flex flex-col sm:flex-row gap-3">
          <button
            onClick={handleTailor}
            disabled={!canViewFitReasons || tailoring}
            className="flex-1 flex items-center justify-center bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 font-medium py-2.5 px-4 rounded-lg transition-colors disabled:opacity-50"
          >
            <Wand2 className="w-4 h-4 mr-2 text-primary" />
            {tailoring ? 'Tailoring...' : 'Tailor Resume'}
          </button>

          <button
            disabled={!canViewFitReasons}
            className="flex-1 flex items-center justify-center bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 font-medium py-2.5 px-4 rounded-lg transition-colors disabled:opacity-50"
          >
            <FileText className="w-4 h-4 mr-2 text-primary" />
            Cover Letter
          </button>

          <button
            onClick={handleApply}
            disabled={applying}
            className="flex-[1.5] flex items-center justify-center bg-primary hover:bg-primary/90 text-white font-medium py-2.5 px-4 rounded-lg transition-colors disabled:opacity-50 shadow-sm"
          >
            <SendHorizontal className="w-4 h-4 mr-2" />
            {applying ? 'Initiating...' : canAutoApply ? 'Auto Apply Now' : 'Apply External'}
          </button>
        </div>
      </div>
    </div>
  );
}
